[package]
name = "projectiles"
version = "0.0.0"
rust-version.workspace = true
edition.workspace = true
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
publish = false

[features]
default = ["client", "gui", "server", "netcode", "udp"]
client = [
  "gui",
  "lightyear/client",
  "lightyear_examples_common/client"
]
gui = [
  "lightyear_examples_common/gui"
]
server = [
  "lightyear/server",
  "lightyear_examples_common/server"
]
netcode = [
  "lightyear_examples_common/netcode"
]
udp = [
  "lightyear_examples_common/udp",
  "lightyear/std",
  "lightyear/udp",
]

[dependencies]
avian2d = { workspace = true, features = [
  "2d",
  "debug-plugin",
  "f32",
  "parry-f32",
  "parallel",
  "serialize",
] }
lightyear = { workspace = true, features = [
  "crossbeam",
  "interpolation",
  "prediction",
  "replication",
  "avian2d",
  "input_bei",
] }
bevy_enhanced_input.workspace = true
lightyear_examples_common.workspace = true
lightyear_frame_interpolation.workspace = true
lightyear_avian2d = { workspace = true, features = ["2d", "lag_compensation"] }

leafwing-input-manager.workspace = true
serde.workspace = true
bevy.workspace = true
rand = "0.8.5"

[package.metadata.bevy_cli.web]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
default-features = false
features = ["client", "netcode"]

[lints]
workspace = true
