[package]
name = "lightyear_benches_divan"
version.workspace = true
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Benchmark tests for lightyear"
repository = "https://github.com/cBournhonesque/lightyear"
keywords = ["bevy", "multiplayer", "networking", "netcode", "gamedev"]
categories = ["game-development", "network-programming"]
license.workspace = true

[dependencies]
lightyear = { workspace = true, features = ["interpolation"] }
lightyear_tests = { workspace = true }


# enable all the bevy defaults:
bevy = { workspace = true, default-features = true }
tracy-client = { version = "=0.18.0" }

# crates specific to benchmarks, so not in top-level Cargo workspace
divan = { version = "0.1.21" }

[lib]
bench = false

[[bench]]
name = "message"
path = "src/message.rs"
harness = false
