[package]
name = "lightyear_ui"
version = "0.26.2"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Runtime debug UI for lightyear"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = ["std"]
std = []
test_utils = []

[dependencies]
lightyear_metrics.workspace = true

# utils
metrics.workspace = true
metrics-util.workspace = true
tracing.workspace = true

# bevy
bevy_app.workspace = true
bevy_color.workspace = true
bevy_ecs.workspace = true
bevy_platform.workspace = true
bevy_reflect.workspace = true
bevy_ui.workspace = true
bevy_utils.workspace = true
bevy_text.workspace = true
bevy_time.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
