[package]
name = "lightyear_transport"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Packet handling for the lightyear networking library"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = ["std"]
std = [
    "lightyear_link/std",
    "indexmap/std"
]
client = [
    "lightyear_connection/client"
]
server = [
    "lightyear_connection/server"
]
metrics = []
trace = []

test_utils = []

[dependencies]
# local crates
lightyear_core.workspace = true
lightyear_link.workspace = true
lightyear_macros.workspace = true
lightyear_serde.workspace = true
lightyear_utils.workspace = true
lightyear_connection = {workspace = true, optional = true}


# bevy
bevy.workspace = true

# serde
serde.workspace = true

# utils
bytes.workspace = true
chrono.workspace = true
crossbeam-channel.workspace = true
enum_dispatch.workspace = true
indexmap.workspace = true
governor.workspace = true
nonzero_ext.workspace = true
ringbuffer.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
