[package]
name = "lightyear_transport"
version = "0.24.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Packet handling for the lightyear networking library"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = ["std"]
std = ["bevy_ecs/std"]
client = ["lightyear_connection/client"]
server = ["lightyear_connection/server"]
metrics = ["dep:metrics", "std"]
trace = []

test_utils = []

[dependencies]
# local crates
lightyear_core.workspace = true
lightyear_link.workspace = true
lightyear_serde.workspace = true
lightyear_utils.workspace = true
lightyear_connection.workspace = true

# bevy
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_platform.workspace = true
bevy_reflect.workspace = true
bevy_time.workspace = true
bevy_utils.workspace = true

# serde
serde.workspace = true

# utils
bytes.workspace = true
crossbeam-channel.workspace = true
enum_dispatch.workspace = true
indexmap.workspace = true
governor.workspace = true
metrics = { workspace = true, optional = true }
nonzero_ext.workspace = true
ringbuffer.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
