[alias]
# we need to run all tests with a single thread otherwise the `mock_instant::global::Instant` gets
# overwritten in parallel tests
t = "test -- --test-threads=1"
clip = "clippy --workspace --features=lightyear_core/not_mock,avian3d/f32 --exclude=compiletime --exclude=avian_3d_character --exclude=launcher --exclude=delta_compression --exclude=distributed_authority --no-deps -- -D warnings -A clippy::needless_lifetimes"

[unstable]
profile-rustflags = true

[profile.profiling]
inherits = "release"
# only works in nightly
#rustflags = [
#  "-C",
#  "force-frame-pointers=yes",
#  "-C",
#  "symbol-mangling-version=v0",
#]
debug = true
