[package]
name = "lightyear_utils"
version = "0.21.0-rc.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Utils shared by lightyear crates"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = ["std"]
std = []

[dependencies]
lightyear_serde.workspace = true

# utils
hashbrown.workspace = true
paste.workspace = true

# bevy
bevy_ecs.workspace = true
bevy_platform.workspace = true
bevy_reflect.workspace = true

[lints]
workspace = true
