[package]
name = "lightyear_utils"
version = "0.26.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Utils shared by lightyear crates"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = []
std = ["bevy_ecs/std", "bevy_platform/std", "bevy_reflect/std"]
metrics = ["dep:metrics", "std"]

[dependencies]
# utils
metrics = { workspace = true, optional = true }
hashbrown.workspace = true
paste.workspace = true
seahash.workspace = true
tracing.workspace = true

# bevy
bevy_ecs.workspace = true
bevy_platform.workspace = true
bevy_reflect.workspace = true
bevy_utils.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
